### ISSUE TITLE
Google app passwords

### ISSUE THREAD

**Issue by Shulyaka** [dmp1ce/daveparrish.net#2]
https://github.com/dmp1ce/daveparrish.net/blob/master/posts/2018-06-22-How-to-download-private-YouTube-videos-with-youtube-dl.markdown#L24 says the password authentication requires 2FA. However Google has application-specific passwords that can authenticate without 2FA: https://myaccount.google.com/apppasswords
Probably they should be noted somehow.

**Comment by dmp1ce** [comment]
Thanks! I updated the blog with a link to the app passwords but I didn't give it a try myself.
